### ISSUE TITLE
Truncate long headers to 72 chars

### ISSUE THREAD

**Issue by andersforsell** [fredrikattebrant/se.attebrant.rtc.addons#1]
Nice addon! It could be even more useful to get the header truncated to fit the 72 char recommended limit, something like "Very long commit messages  <SKIP> could be trunc... : 214012"

**Comment by fredrikattebrant** [comment]
+1 @andersforsell

**Comment by fredrikattebrant** [comment]
Fix in commit 2aa8514f9f7ae6488b1c97d10cebc0d2bfad1827
